import { describe, expect, it } from 'vitest';
import golden from './golden.json';
import { buildModel } from '../../fender/index';
import { buildDxf } from '../dxf';
import type { DrawingModel, FenderConfig } from '../../fender/types';

/**
 * golden.json's `dxfBlankOnly` is generated by a verbatim transcription of the design
 * source's `buildDxf()` (scripts/extract-golden.mjs, mirroring fender.html:602-622),
 * plus the new HEADER/TABLES sections from PLAN §9.3. It is fed real blank geometry
 * with the parts arrays EMPTIED — the blank never contains a curve command (PLAN §9.2),
 * so a straight-line-only `pathPolysStraightOnly` (throws on `[acqst]`) can reproduce it
 * exactly in plain Node. This is the piece a silent DXF regression would hurt most.
 *
 * `blankOnly()` does the same thing to a real `DrawingModel` before it reaches the
 * actual `buildDxf()` under test — the strut/mudflap curves in a full model would call
 * into `pathPolys()`'s DOM branch, which this Node test environment cannot provide (no
 * `jsdom` — see pathPolys.test.ts).
 */

type Case = { config: FenderConfig; baseName: string; dxfBlankOnly: string };
const CASES = Object.entries(golden as unknown as Record<string, Case>);

function blankOnly(model: DrawingModel): DrawingModel {
  return { ...model, parts: { ...model.parts, outlines: [], folds: [], holes: [], slots: [] } };
}

describe.each(CASES)('buildDxf(%s) — blank only', (_name, c) => {
  it('matches the design source exactly, byte for byte', () => {
    const model = blankOnly(buildModel(c.config));
    expect(buildDxf(model)).toBe(c.dxfBlankOnly);
  });
});

// ---- DXF entity parser for structural assertions below. Our own writer never emits
// anything but fixed 2-line (code, value) group-code pairs, so a line-pair walk is
// sufficient — no need for a general DXF parser.
interface Entity {
  type: string;
  layer: string;
  points: [number, number][];
  closed: boolean;
}

function parseEntities(dxf: string): Entity[] {
  const lines = dxf.split('\n');
  const entities: Entity[] = [];
  let inEntities = false;
  let i = 0;
  while (i + 1 < lines.length) {
    const code = lines[i]!;
    const value = lines[i + 1]!;
    if (code === '2' && value === 'ENTITIES') inEntities = true;
    if (inEntities && code === '0' && value === 'ENDSEC') inEntities = false;
    if (inEntities && code === '0' && value !== 'SECTION') {
      const type = value;
      const codes: [string, string][] = [];
      i += 2;
      while (i + 1 < lines.length && lines[i] !== '0') {
        codes.push([lines[i]!, lines[i + 1]!]);
        i += 2;
      }
      const layer = codes.find(([c]) => c === '8')?.[1] ?? '';
      const closed = codes.find(([c]) => c === '70')?.[1] === '1';
      const points: [number, number][] = [];
      for (let j = 0; j < codes.length; j++) {
        if (codes[j]![0] === '10') points.push([Number(codes[j]![1]), Number(codes[j + 1]![1])]);
      }
      entities.push({ type, layer, points, closed });
      continue;
    }
    i += 2;
  }
  return entities;
}

describe('DXF structure — PLAN §9.3', () => {
  const model = blankOnly(buildModel(CASES[0]![1].config));
  const dxf = buildDxf(model);

  it('opens with a HEADER section declaring $ACADVER AC1015 (R2000)', () => {
    const headerIdx = dxf.indexOf('0\nSECTION\n2\nHEADER');
    const acadverIdx = dxf.indexOf('$ACADVER\n1\nAC1015');
    expect(headerIdx).toBe(0);
    expect(acadverIdx).toBeGreaterThan(headerIdx);
  });

  it('declares a TABLES section with the CUT / FOLD / HOLES layers, colours 7 / 5 / 1', () => {
    const tablesIdx = dxf.indexOf('SECTION\n2\nTABLES');
    expect(tablesIdx).toBeGreaterThan(-1);
    expect(dxf).toContain('LAYER\n2\nCUT\n70\n0\n62\n7');
    expect(dxf).toContain('LAYER\n2\nFOLD\n70\n0\n62\n5');
    expect(dxf).toContain('LAYER\n2\nHOLES\n70\n0\n62\n1');
  });

  it('ENTITIES/ENDSEC/EOF are well-formed and ENTITIES is the last section', () => {
    expect(dxf).toContain('SECTION\n2\nENTITIES');
    expect(dxf.endsWith('0\nENDSEC\n0\nEOF')).toBe(true);
    // Exactly three SECTION openings — HEADER, TABLES, ENTITIES.
    expect(dxf.split('SECTION').length - 1).toBe(3);
  });

  it('layer table precedes the entities that reference those layers', () => {
    expect(dxf.indexOf('2\nLAYER')).toBeLessThan(dxf.indexOf('SECTION\n2\nENTITIES'));
  });
});

describe('DXF entity counts and layers — blank-only model', () => {
  it.each(CASES)('%s: LWPOLYLINE/CIRCLE counts match the model, all on CUT/FOLD/HOLES', (_name, c) => {
    const model = blankOnly(buildModel(c.config));
    const entities = parseEntities(buildDxf(model));

    const circles = entities.filter((e) => e.type === 'CIRCLE');
    const polylines = entities.filter((e) => e.type === 'LWPOLYLINE');

    expect(circles.length).toBe(model.blank.holes.length);
    // 1 blank outline + 1 per slot (rect) + 1 per fold/score/seam line — each of those
    // paths is a single M subpath in pattern.ts, so pathPolys emits exactly one
    // polyline per entry (see PLAN §9.2 comment in pattern.ts). WP23 §23.5: a `slot`
    // (punched tongue) join appends its own release-cut subpath into the SAME outline
    // `d`, one per skirt (top, bottom) per dart, so those add to the outline's own
    // polyline count instead of the primary-path count above.
    const tongueSubpaths =
      c.config.join === 'slot' ? 2 * Math.max(0, model.geo.n - 1) : 0;
    const primaryPolylines =
      1 +
      tongueSubpaths +
      model.blank.slots.length +
      model.blank.foldLines.length +
      model.blank.scoreLines.length +
      model.blank.seams.length;
    expect(polylines.length).toBe(primaryPolylines);

    expect(entities.every((e) => e.layer === 'CUT' || e.layer === 'FOLD' || e.layer === 'HOLES')).toBe(true);
    expect(circles.every((e) => e.layer === 'HOLES')).toBe(true);
  });

  it('the blank outline is closed (70=1); fold/score/seam lines are open (70=0)', () => {
    const model = blankOnly(buildModel(CASES[0]![1].config));
    const entities = parseEntities(buildDxf(model));
    // The outline is the only CUT polyline with more than 4 vertices — slots are
    // 4-point rects, and both are closed; fold/score/seam lines are all FOLD and open.
    const cutPolylines = entities.filter((e) => e.type === 'LWPOLYLINE' && e.layer === 'CUT');
    const outlinePoly = cutPolylines.find((e) => e.points.length > 4)!;
    expect(outlinePoly.closed).toBe(true);
    const slotPolys = cutPolylines.filter((e) => e.points.length === 4);
    slotPolys.forEach((s) => expect(s.closed).toBe(true));
    const foldPolys = entities.filter((e) => e.type === 'LWPOLYLINE' && e.layer === 'FOLD');
    foldPolys.forEach((f) => expect(f.closed).toBe(false));
  });
});

describe('Y-flip is negation relative to the model — PLAN "scrutinise the Y-flip"', () => {
  it('a CIRCLE at offset 0 has DXF y = -(model cy)', () => {
    const model = blankOnly(buildModel(CASES[0]![1].config));
    const entities = parseEntities(buildDxf(model));
    const circles = entities.filter((e) => e.type === 'CIRCLE');
    const hole = model.blank.holes[0]!;
    const dxfHole = circles[0]!;
    expect(dxfHole.points[0]![1]).toBeCloseTo(-Number(hole.cy), 3);
    expect(dxfHole.points[0]![0]).toBeCloseTo(Number(hole.cx), 3);
  });
});

// WP23 §23.3 removed the only curve-free Sheet-B part (the butt-strap/clip hardware)
// along with the join it belonged to — a rivet goes straight through the lap now, and
// the tab is integral to the blank, so Sheet-B is struts/mudflap only, and both have
// curved (arc/quadratic) outlines. This test environment has no DOM at all (see
// vite.config.ts's `environment: 'node'`), and only outline PATHS need it — hole
// circles don't — so outlines/folds are stripped before buildDxf() the same way
// `blankOnly()` strips the blank's own parts above.
function partsHolesOnly(model: DrawingModel): DrawingModel {
  return { ...model, parts: { ...model.parts, outlines: [], folds: [] } };
}

describe('parts offset — dy = Wd + 30, same as svg.ts\'s PARTS_GAP', () => {
  it('a hole on the parts sheet is offset by g.Wd + 30 before the Y-flip', () => {
    const config: FenderConfig = { ...CASES[0]![1].config, struts: 1, mudflap: 0 };
    const model = partsHolesOnly(buildModel(config));
    expect(model.parts.holes.length).toBeGreaterThan(0);
    const entities = parseEntities(buildDxf(model));
    const circles = entities.filter((e) => e.type === 'CIRCLE');
    const strutHole = model.parts.holes[0]!;
    const dy = model.geo.Wd + 30;
    const expectedY = Number((-(Number(strutHole.cy) + dy)).toFixed(3));
    const strutCircle = circles.find((c) => c.points[0]![1] === expectedY);
    expect(strutCircle).toBeDefined();
  });

  it('full curve-free model: entity counts match blank + parts exactly', () => {
    const config: FenderConfig = { ...CASES[0]![1].config, struts: 1, mudflap: 0 };
    const model = partsHolesOnly(buildModel(config));
    const entities = parseEntities(buildDxf(model));
    const circles = entities.filter((e) => e.type === 'CIRCLE');
    const polylines = entities.filter((e) => e.type === 'LWPOLYLINE');

    expect(circles.length).toBe(model.blank.holes.length + model.parts.holes.length);
    const expectedPolylines =
      1 +
      model.blank.slots.length +
      model.blank.foldLines.length +
      model.blank.scoreLines.length +
      model.blank.seams.length;
    expect(polylines.length).toBe(expectedPolylines);
  });
});

describe('baseName is filesystem-safe', () => {
  it.each(CASES)('%s', (_name, c) => {
    const model = buildModel(c.config);
    expect(model.baseName).toBe(c.baseName);
    expect(model.baseName).toMatch(/^[a-z0-9-]+$/);
  });
});

describe('WP20 §20.1 — nesting is removed outright', () => {
  it('the (reserved, inert) nest field changes nothing about the DXF output', () => {
    const off = buildDxf(blankOnly(buildModel({ ...CASES[0]![1].config, nest: false })));
    const on = buildDxf(blankOnly(buildModel({ ...CASES[0]![1].config, nest: true })));
    expect(on).toBe(off);
  });
});
