import { describe, expect, it } from 'vitest';
import golden from './golden.json';
import { buildModel } from '../../fender/index';
import { buildSvg } from '../svg';
import type { FenderConfig } from '../../fender/types';

/**
 * golden.json's `svgFull` is generated by a verbatim transcription of the design
 * source's `buildSvg()` (scripts/extract-golden.mjs, mirroring fender.html:507-535),
 * fed the same blank + parts geometry `src/fender/__tests__/golden.json` pins
 * elsewhere. SVG keeps path `d` strings verbatim — no curve sampling happens on the
 * way out — so the whole file (blank AND parts, curves included) can be pinned exactly
 * in plain Node; see PLAN §9.2.
 */

type Case = { config: FenderConfig; baseName: string; svgFull: string };
const CASES = Object.entries(golden as unknown as Record<string, Case>);

describe.each(CASES)('buildSvg(%s)', (_name, c) => {
  it('matches the design source exactly, byte for byte', () => {
    const model = buildModel(c.config);
    expect(buildSvg(model)).toBe(c.svgFull);
  });
});

describe('SVG invariants', () => {
  const base = CASES[0]![1];
  const model = buildModel(base.config);
  const svg = buildSvg(model);

  it('declares width/height in mm', () => {
    expect(svg).toMatch(/width="[\d.]+mm" height="[\d.]+mm"/);
  });

  it('viewBox is in the same units as width/height — 1 user unit = 1 mm', () => {
    const widthMm = Number(/width="([\d.]+)mm"/.exec(svg)![1]);
    const heightMm = Number(/height="([\d.]+)mm"/.exec(svg)![1]);
    const viewBox = /viewBox="([^"]+)"/.exec(svg)![1]!.split(' ').map(Number);
    expect(viewBox[2]).toBeCloseTo(widthMm, 5);
    expect(viewBox[3]).toBeCloseTo(heightMm, 5);
  });

  it('declares the three Inkscape layers, CUT / FOLD / HOLES, in that order', () => {
    const cut = svg.indexOf('inkscape:label="CUT"');
    const fold = svg.indexOf('inkscape:label="FOLD"');
    const holes = svg.indexOf('inkscape:label="HOLES"');
    expect(cut).toBeGreaterThan(-1);
    expect(fold).toBeGreaterThan(cut);
    expect(holes).toBeGreaterThan(fold);
  });

  it('CUT strokes are literal #000, FOLD literal #00f/#0000ff, HOLES literal #f00/#ff0000', () => {
    // Colours here are laser/Inkscape contract, not design tokens — PLAN §9.2 / hard rule 2.
    const cutLayer = svg.slice(svg.indexOf('id="CUT"'), svg.indexOf('id="FOLD"'));
    const foldLayer = svg.slice(svg.indexOf('id="FOLD"'), svg.indexOf('id="HOLES"'));
    const holesLayer = svg.slice(svg.indexOf('id="HOLES"'));
    expect(cutLayer).toContain('stroke="#000"');
    expect(cutLayer).not.toMatch(/var\(--/);
    expect(foldLayer).toMatch(/stroke="#00f"|stroke="#0000ff"/);
    expect(holesLayer).toMatch(/stroke="#f00"|stroke="#ff0000"/);
  });

  it('the title is the model baseName', () => {
    expect(svg).toContain(`<title>${model.baseName}</title>`);
  });

  it('holes and slots land inside the CUT/HOLES layers, not FOLD', () => {
    const foldLayer = svg.slice(svg.indexOf('id="FOLD"'), svg.indexOf('id="HOLES"'));
    expect(foldLayer).not.toContain('<circle');
    expect(foldLayer).not.toContain('<rect');
  });
});

describe('PLAN §9.4 — nesting reaches the SVG export', () => {
  it('non-nested output has no second <g transform> block per layer', () => {
    const model = buildModel({ ...CASES[0]![1].config, nest: false });
    const svg = buildSvg(model);
    // Only the parts-offset <g transform="translate(0,…)"> groups should appear —
    // never a rotate(180) group, which only the nested copy emits.
    expect(svg).not.toContain('rotate(180)');
  });

  it('nesting appends a rotate(180) group to CUT, FOLD and HOLES, each containing the outline/fold/hole geometry once more', () => {
    const model = buildModel({ ...CASES[0]![1].config, nest: true });
    const svg = buildSvg(model);
    expect(model.tiling.nestTransform).toBeTruthy();
    const nestGroup = `<g transform="${model.tiling.nestTransform}">`;
    // One nested group per layer (CUT, FOLD, HOLES).
    expect(svg.split(nestGroup).length - 1).toBe(3);

    const cutLayer = svg.slice(svg.indexOf('id="CUT"'), svg.indexOf('id="FOLD"'));
    // The primary outline plus one nested outline = 2 occurrences of the outline `d`.
    const outlineOccurrences = cutLayer.split(`d="${model.blank.outline}"`).length - 1;
    expect(outlineOccurrences).toBe(2);

    const holesLayer = svg.slice(svg.indexOf('id="HOLES"'));
    const holeCircleCount = (holesLayer.match(/<circle/g) ?? []).length;
    expect(holeCircleCount).toBe(model.blank.holes.length * 2 + model.parts.holes.length);
  });

  it('turning nesting on leaves everything before the nested groups byte-identical to the non-nested file', () => {
    const off = buildSvg(buildModel({ ...CASES[0]![1].config, nest: false }));
    const on = buildSvg(buildModel({ ...CASES[0]![1].config, nest: true }));
    // The non-nested file must appear as a prefix-compatible subsequence: every line
    // of `off` should still be present, in order, once the nested `<g rotate(180)>`
    // blocks are stripped out of `on`.
    const stripped = on.replace(/<g transform="translate\([\d.]+, [\d.]+\) rotate\(180\)">[\s\S]*?<\/g>\n/g, '');
    expect(stripped).toBe(off);
  });
});
